### ISSUE TITLE
Configure Development Stack

### ISSUE THREAD

**Issue by williaby** [williaby/PromptCraft#7]
## Description
Set up Poetry, Nox, pre-commit hooks, and Docker compose for the development environment.

## Acceptance Criteria
- [ ] pyproject.toml configured with all dependencies
- [ ] noxfile.py created with standard sessions
- [ ] Pre-commit hooks configured and tested
- [ ] Docker compose stack for local services
- [ ] Gradio UI scaffold created
- [ ] `nox -s tests` passing

## Technical Details
```toml
# pyproject.toml key dependencies
[tool.poetry.dependencies]
python = "^3.11"
llama-index = "0.10.37"
dspy-ai = "2.4.5"
gradio = "4.31.0"
prefect = "2.14.0"
qdrant-client = "1.9.0"
fastapi = "0.110.0"
```

## Dependencies
- Completed Issue #5 (Repository initialization)
- Python 3.11+ installed locally

## Testing
```bash
# Install and test
poetry install
nox -s tests
nox -s lint

# Test pre-commit
pre-commit run --all-files

# Verify Docker compose
docker-compose config
docker-compose ps
```

## References
- [Poetry Documentation](https://python-poetry.org/docs/)
- [Nox Documentation](https://nox.thea.codes/)
- Project plan section 8.1: Test Strategy
