### ISSUE TITLE
Deploy Core On-Premise Services

### ISSUE THREAD

**Issue by williaby** [williaby/PromptCraft#8]
## Description
Deploy Qdrant vector database and Prefect orchestrator on the Unraid server with proper configuration.

## Acceptance Criteria
- [ ] Qdrant deployed on NVMe storage
- [ ] Prefect server running and accessible
- [ ] Cloudflare tunnel configured and active
- [ ] Basic monitoring for services
- [ ] Backup scripts created
- [ ] Services accessible via tunnel

## Technical Details
```yaml
# Qdrant configuration
volumes:
  - /mnt/nvme/qdrant:/qdrant/storage
environment:
  - QDRANT__SERVICE__HTTP_PORT=6333
  - QDRANT__SERVICE__GRPC_PORT=6334
resources:
  limits:
    memory: 32G
```

## Dependencies
- Unraid server access
- Cloudflare account
- Docker installed on Unraid

## Testing
```bash
# Test Qdrant
curl http://localhost:6333/health

# Test Prefect
curl http://localhost:4200/api/health

# Test Cloudflare tunnel
cloudflared tunnel info promptcraft

# Verify NVMe usage
df -h /mnt/nvme/qdrant
```

## References
- [Qdrant Documentation](https://qdrant.tech/documentation/)
- [Prefect Documentation](https://docs.prefect.io/)
- Project plan section 5.1: Docker Compose Configuration
